name: Publish site to S3
on:
  push:
    branches:
      - master 
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout main
        uses: actions/checkout@v4.2.2
      - name: Build only 
        uses: shalzz/zola-deploy-action@v0.20.0
        env:
          BUILD_ONLY: true
      - name: Create artifacts
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: public
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: site
      - name: Set up S3cmd cli tool
        uses: leotsarev/s3cmd@d7e23bec15fd3d286ceb90214c06a6e897d9e73f
        with:
            provider: yandex
            region: ru-central1
            access_key: ${{ secrets.SYNC_ACCESS_ID }}
            secret_key: ${{ secrets.SYNC_ACCESS_SECRET }}
      - name: sync to s3
        run: |
          ls
          s3cmd sync --recursive public s3://code.rpg.ru
    
