name: Publish site to gh-pages
on:
  push:
    branches:
      - main 
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout main
        uses: actions/checkout@v4.2.2
      - name: Build only 
        uses: shalzz/zola-deploy-action@v0.19.2
        env:
          BUILD_ONLY: true
      - name: Create artifacts
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: public
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: site
      - name: Sync to S3
        uses: michaelliao/sync-s3-compatible-action@v2
        env:
          SYNC_OPT_UNUSED: delete # force delete unused files on cloud storage:
          SYNC_DIR: public
          SYNC_TYPE: aws
          # bucket must be created in region:
          SYNC_REGION: ru-central1
          SYNC_BUCKET: code.rpg.ru
          # set at: Settings - Secrets and variables - Actions - Repository secrets:
          SYNC_ACCESS_ID: ${{ secrets.SYNC_ACCESS_ID }}
          SYNC_ACCESS_SECRET: ${{ secrets.SYNC_ACCESS_SECRET }}
    
